### ISSUE TITLE
E97: Cannot create diffs

### ISSUE THREAD

**Issue by abourree** [AndrewRadev/linediff.vim#15]
Hi

I clone your repository and try to compare the two following lines:
Toto
Tutu

I get the following error;
Error detected while processing function <SNR>20_Linediff..<SNR>20_PerformDiff..linediff#differ#CreateDiffBuffer:
line   26:
E97: Cannot create diffs
Press ENTER or type command to continue

And then diff doesn't show diff

I notice that vimdiff raise same error now

Regards,

Arnaud

**Comment by AndrewRadev** [comment]
This doesn't seem like a problem with linediff, especially considering that, as you say, the same error happens with the standard vimdiff command.

Execute the command `:help E97` to see some information about the error (or check it out online [here](http://vimdoc.sourceforge.net/htmldoc/diff.html#E97)). It seems like the `diff` command can't be called or there are problems with the shell interface.

There are some tips on how to debug the problems in that help section. Try them out and let me know.

**Comment by abourree** [comment]
Hi,

You are right, issue is not from Linediff. I remove MyDiff from .vimrc file and now it works perfectly. Thanks for your help and your script.

Arnaud.
