### ISSUE TITLE
Adding vim-repeat support

### ISSUE THREAD

**Issue by NasaGeek** [AndrewRadev/linediff.vim#20]
Would it make sense to add [vim-repeat](https://github.com/tpope/vim-repeat) support to this project? Seems useful as :Linediff is generally called twice in a row.

**Comment by AndrewRadev** [comment]
Sorry for taking so long to respond to this issue. I could have commented a long time ago, but I've been having difficulties finding the time and energy to work on open source, and this issue ended up in a long backlog.

As for your question, you're right that you call `:Linediff` twice, but you need to mark it in visual mode, and I don't think vim-repeat would work out with that. I can only imagine the dot marking the same number of lines or something like that, but I'm not sure how useful this would be in practice. If you have a particular idea of how this might work, reopen the issue, let me know and I'll see what I can do.

**Comment by NasaGeek** [comment]
Yeah I realized after thinking about it for a while that it wasn't really a strong use case, so I closed the issue. Thanks for getting back to me, though!
