### ISSUE TITLE
Lineedit command?

### ISSUE THREAD

**Issue by blueyed** [AndrewRadev/linediff.vim#29]
Sometimes it is useful to edit part of a buffer in a new temporary buffer, e.g. to run a linter against a docstring.
`Linediff` can be abused for this (by diffing the same section against itself), but a separate `:Lineedit` command would be better.

Or is there a better way in general?!

**Comment by AndrewRadev** [comment]
Well, I do have this plugin: https://github.com/AndrewRadev/inline_edit.vim

That one lets you select just one area and edit it. It's an older plugin, I think, so I'm not sure if it has the same feature set of linediff. Could you try it out and see if it works for you?

**Comment by blueyed** [comment]
Thanks!  (I've seen it before actually :))

I've noticed that when saving the new/temp buffer (from a visual selection) the initial filetype (from the original file) gets reset, although I've changed it manually (from python to markdown).
But I should report that issue over at https://github.com/AndrewRadev/inline_edit.vim.. :)
