### ISSUE TITLE
Vim patch 9.0.907 causes E1312 when temporary buffers are closed

### ISSUE THREAD

**Issue by ghgary** [AndrewRadev/linediff.vim#36]
Vim changed its behavior at patch 9.0.907 to prohibit autocommands from performing certain operations such as closing buffers. Consequently, closing a linediff temporary buffer now prints an error message like this one:

<code>Error detected while processing WinEnter Autocommands for "<buffer=3>"..function linediff#controller#Destroy[6]..linediff#differ#CloseAndReset[1]
..linediff#differ#CloseDiffBuffer:
line    3:
E1312: Not allowed to change the window layout in this autocmd</code>

A workaround is to change line 214 of autoload/linediff/differ.vim (in function linediff#differ#CloseDiffBuffer(()) from

<code>exe "bdelete".bang." ".self.diff_buffer</code>

to

<code>call feedkeys(":bdelete".bang." ".self.diff_buffer."\<CR>:\<BS>")</code>

which just executes the :bdelete command in a feedkeys() operation, clearing the :bdelete from the command line with a colon and a backspace.

**Comment by AndrewRadev** [comment]
Thanks for noticing, I have a mapping to close an entire tab, so I didn't realize this was happening when you close just one diff buffer.

I had some trouble getting the workaround to work for me in tests. I think it's a bit fiddly about key inputs. I tried to fix it instead by setting a timer to close the buffer immediately after the autocommand: https://github.com/AndrewRadev/linediff.vim/commit/b4d3c3f03eed00caa741c2650e13db5b7b7ce0ef

This seems to work fine for me and it passes the tests. Could you try it out as well with your own setup, let me know if it fixes the issue for you as well?

**Comment by ghgary** [comment]
You're welcome.

My "git pull" command timed out (weird), so I just downloaded the file from the web page. It seems to work fine. I'll let you know if that changes. Thanks for fixing it, and so quickly.

**Comment by AndrewRadev** [comment]
Cool, I'll close this issue for now, but please reopen if you see any regression
